import type { User, ExpenseItem } from "@/types";

export const DEMO_USERS: User[] = [
  {
    id: "user_self",
    email: "pedro.reis@example.invalid",
    handle: "pedro.reis",
    name: "Pedro Reis",
    pixKeyType: "email",
    pixKeyHint: "p****s@example.invalid",
    avatarUrl: undefined,
    onboarded: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_ana",
    email: "ana.silva@example.invalid",
    handle: "ana.silva",
    name: "Ana Silva",
    pixKeyType: "email",
    pixKeyHint: "a****a@example.invalid",
    avatarUrl: undefined,
    onboarded: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_marcos",
    email: "marcos.oliveira@example.invalid",
    handle: "marcos.oliveira",
    name: "Marcos Oliveira",
    pixKeyType: "email",
    pixKeyHint: "m****a@example.invalid",
    avatarUrl: undefined,
    onboarded: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_julia",
    email: "julia.santos@example.invalid",
    handle: "julia.santos",
    name: "Julia Santos",
    pixKeyType: "email",
    pixKeyHint: "j****s@example.invalid",
    avatarUrl: undefined,
    onboarded: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_carla",
    email: "carla.mendes@example.invalid",
    handle: "carla.mendes",
    name: "Carla Mendes",
    pixKeyType: "email",
    pixKeyHint: "c****s@example.invalid",
    avatarUrl: undefined,
    onboarded: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "user_rafael",
    email: "rafael.costa@example.invalid",
    handle: "rafael.costa",
    name: "Rafael Costa",
    pixKeyType: "email",
    pixKeyHint: "r****a@example.invalid",
    avatarUrl: undefined,
    onboarded: true,
    createdAt: new Date().toISOString(),
  },
];

export const DEMO_PIX_KEYS: Record<string, string> = {
  user_self: "pedro.reis@example.invalid",
  user_ana: "ana.silva@example.invalid",
  user_marcos: "marcos.oliveira@example.invalid",
  user_julia: "julia.santos@example.invalid",
  user_carla: "carla.mendes@example.invalid",
  user_rafael: "rafael.costa@example.invalid",
};

export const DEMO_ITEMS: Omit<ExpenseItem, "id" | "expenseId" | "createdAt">[] = [
  {
    description: "Picanha na brasa 400g",
    quantity: 1,
    unitPriceCents: 8900,
    totalPriceCents: 8900,
  },
  {
    description: "Costela no bafo",
    quantity: 1,
    unitPriceCents: 6700,
    totalPriceCents: 6700,
  },
  {
    description: "Coca-Cola 600ml",
    quantity: 2,
    unitPriceCents: 1200,
    totalPriceCents: 2400,
  },
  {
    description: "Cerveja Brahma 600ml",
    quantity: 3,
    unitPriceCents: 1400,
    totalPriceCents: 4200,
  },
  {
    description: "Batata frita grande",
    quantity: 1,
    unitPriceCents: 3200,
    totalPriceCents: 3200,
  },
  {
    description: "Farofa especial",
    quantity: 1,
    unitPriceCents: 1800,
    totalPriceCents: 1800,
  },
  {
    description: "Vinagrete",
    quantity: 1,
    unitPriceCents: 800,
    totalPriceCents: 800,
  },
  {
    description: "Agua mineral 500ml",
    quantity: 2,
    unitPriceCents: 600,
    totalPriceCents: 1200,
  },
  {
    description: "Caipirinha",
    quantity: 2,
    unitPriceCents: 2800,
    totalPriceCents: 5600,
  },
  {
    description: "Pudim",
    quantity: 3,
    unitPriceCents: 933,
    totalPriceCents: 2800,
  },
  {
    description: "Salmao grelhado",
    quantity: 1,
    unitPriceCents: 7500,
    totalPriceCents: 7500,
  },
  {
    description: "Acai 500ml",
    quantity: 2,
    unitPriceCents: 1100,
    totalPriceCents: 2200,
  },
];
